SELECT  
	DISTINCT R.REL_ID		AS ID_PROJETO,
	R.REL_NAME				AS NOME_PROJETO,
	R.REL_START_DATE		AS DT_INICIO,
	R.REL_USER_TEMPLATE_13	AS DT_ROLLOUT,
	TC.TC_TESTCYCL_ID		AS ID_CT,
	CASE 
		WHEN UPPER(TC.TC_STATUS) IN ('PASSED', 'UNABLE', 'N/A') THEN 1 ELSE 0
	END						AS CTs_EXECUTADOS,
	TC.TC_STATUS			AS STATUS,
	TC.TC_ACTUAL_TESTER		AS TESTER,
	R.BG_SUBJECT_PBI		AS INSTANCIA
FROM 
	RELEASES R
	INNER JOIN RELEASE_CYCLES RC ON ( R.REL_ID = RC.RCYC_PARENT_ID AND R.BG_SUBJECT_PBI= RC.BG_SUBJECT_PBI)
	INNER JOIN TESTCYCL TC ON (RC.RCYC_ID = TC_ASSIGN_RCYC  AND RC.BG_SUBJECT_PBI = TC.BG_SUBJECT_PBI)
WHERE 
	R.REL_ID = 1156
	AND R.BG_SUBJECT_PBI = 6 
	AND UPPER(RC.RCYC_USER_TEMPLATE_04) = 'TECHMAHINDRA'
